### ISSUE TITLE
Write SRS Document (Due date: 18 May)

### ISSUE THREAD

**Issue by goofcode** [goofcode/SE_Project#1]
Write software requirement specification ([what is SRS?](https://en.wikipedia.org/wiki/Software_requirements_specification))

Let's start with google doc, port it to markdown document.

**Comment by dorongjik** [comment]
The contents of the uploaded assignment word file.

(Use Case-based) Software Requirement Specification (See attachment for samples)
ν	Introduction to the system 
ν	Use case diagrams
ν	Use case descriptions
ν	System sequence diagrams
ν	Non-functional requirements (Quality requirements, Constraints, etc)
ν	Requirement Dependency Traceability 
ν	Development and Target Platforms
ν	Project Glossary
ν	Document Revision History

**Comment by wogus2421** [comment]
done

**Comment by wogus2421** [comment]
done
