### ISSUE TITLE
Loading files

### ISSUE THREAD

**Issue by goofcode** [goofcode/SE_Project#3]
1. git checkout -t origin/dev/basic
2. create your own branch
3. work (see below)
4. open pull request to dev/basic

@holquew 
Make model class can save loaded file line by line and loading state of each side of panel

@wogus2421 
Make list view show all the lines of text file on listview (need to make event handler for load button)

@wellmin11 
Add skeleton event handlers for all button on controller and bind the function to the button.
Make controller have an instance of model class

[reference for MVC using javafx](http://blog.neonkid.xyz/104)

**Comment by wogus2421** [comment]
I've done https://github.com/goofcode/SE_Project/tree/dev/list_view

**Comment by goofcode** [comment]
finished
